# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Article publié ?'),
        ),
    ]
