# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171016_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auteur',
            new_name='pseudo',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
